
-- Generato da Oracle SQL Developer Data Modeler 4.0.2.840
--   in:        2018-03-06 10:28:58 CET
--   sito:      Oracle Database 11g
--   tipo:      Oracle Database 11g




CREATE TABLE CFG_EMAIL_PARAMETERS
  (
    ID                 NUMBER (10) NOT NULL ,
    VERSION            NUMBER (10) NOT NULL ,
    INSERT_TIME        DATE DEFAULT sysdate NOT NULL ,
    UPDATE_TIME        DATE NOT NULL ,
    PARAM_CODE         VARCHAR2 (80 BYTE) NOT NULL ,
    PARAM_VALUE        VARCHAR2 (255 BYTE) NOT NULL ,
    DESCRIPTION        VARCHAR2 (255 BYTE) NOT NULL ,
    REF_EMAIL_TEMPLATE NUMBER (10) NOT NULL
  ) ;
COMMENT ON COLUMN CFG_EMAIL_PARAMETERS.ID
IS
  'Email  parameter ID' ;
  COMMENT ON COLUMN CFG_EMAIL_PARAMETERS.VERSION
IS
  'Email parameter version' ;
  COMMENT ON COLUMN CFG_EMAIL_PARAMETERS.INSERT_TIME
IS
  'Email parameter insert time' ;
  COMMENT ON COLUMN CFG_EMAIL_PARAMETERS.UPDATE_TIME
IS
  'Email parameter update time' ;
  COMMENT ON COLUMN CFG_EMAIL_PARAMETERS.PARAM_CODE
IS
  'Email parameter code' ;
  COMMENT ON COLUMN CFG_EMAIL_PARAMETERS.PARAM_VALUE
IS
  'Email parameter value' ;
  COMMENT ON COLUMN CFG_EMAIL_PARAMETERS.DESCRIPTION
IS
  'Email parameter description' ;
  ALTER TABLE CFG_EMAIL_PARAMETERS ADD CONSTRAINT CFG_EMAIL_PARAMETERS_PK PRIMARY KEY ( ID ) ;

CREATE TABLE CFG_EMAIL_TEMPLATES
  (
    ID          NUMBER (10) NOT NULL ,
    VERSION     NUMBER (10) NOT NULL ,
    INSERT_TIME DATE DEFAULT sysdate NOT NULL ,
    UPDATE_TIME DATE NOT NULL ,
    NAME        VARCHAR2 (80 BYTE) NOT NULL ,
    DESCRIPTION VARCHAR2 (255 BYTE) NOT NULL
  ) ;
COMMENT ON COLUMN CFG_EMAIL_TEMPLATES.ID
IS
  'Email template ID' ;
  COMMENT ON COLUMN CFG_EMAIL_TEMPLATES.VERSION
IS
  'Email Template version' ;
  COMMENT ON COLUMN CFG_EMAIL_TEMPLATES.INSERT_TIME
IS
  'Email Template insert time' ;
  COMMENT ON COLUMN CFG_EMAIL_TEMPLATES.UPDATE_TIME
IS
  'Email Template update time' ;
  COMMENT ON COLUMN CFG_EMAIL_TEMPLATES.NAME
IS
  'Email Template name' ;
  COMMENT ON COLUMN CFG_EMAIL_TEMPLATES.DESCRIPTION
IS
  'Email Template description' ;
  ALTER TABLE CFG_EMAIL_TEMPLATES ADD CONSTRAINT CFG_EMAIL_TEMPLATES_PK PRIMARY KEY ( ID ) ;

CREATE TABLE CFG_ORGANIZATION_PARAMETERS
  (
    ID               NUMBER (10) NOT NULL ,
    VERSION          NUMBER (10) NOT NULL ,
    INSERT_TIME      DATE DEFAULT sysdate NOT NULL ,
    UPDATE_TIME      DATE NOT NULL ,
    PARAM_CODE       VARCHAR2 (80 BYTE) ,
    PARAM_VALUE      VARCHAR2 (255 BYTE) ,
    DESCRIPTION      VARCHAR2 (255 BYTE) ,
    REF_ORGANIZATION NUMBER (10) NOT NULL
  ) ;
COMMENT ON COLUMN CFG_ORGANIZATION_PARAMETERS.ID
IS
  'Organization parameter ID' ;
  COMMENT ON COLUMN CFG_ORGANIZATION_PARAMETERS.VERSION
IS
  'Organization parameter version' ;
  COMMENT ON COLUMN CFG_ORGANIZATION_PARAMETERS.INSERT_TIME
IS
  'Organization parameter insert time' ;
  COMMENT ON COLUMN CFG_ORGANIZATION_PARAMETERS.UPDATE_TIME
IS
  'Organization parameter update time' ;
  COMMENT ON COLUMN CFG_ORGANIZATION_PARAMETERS.PARAM_CODE
IS
  'Organization parameter code' ;
  COMMENT ON COLUMN CFG_ORGANIZATION_PARAMETERS.PARAM_VALUE
IS
  'Organization parameter value' ;
  COMMENT ON COLUMN CFG_ORGANIZATION_PARAMETERS.DESCRIPTION
IS
  'Organization parameter description' ;
  COMMENT ON COLUMN CFG_ORGANIZATION_PARAMETERS.REF_ORGANIZATION
IS
  'Organization reference' ;
  ALTER TABLE CFG_ORGANIZATION_PARAMETERS ADD CONSTRAINT CFG_ORGANIZATION_PARAMETERS_PK PRIMARY KEY ( ID ) ;

CREATE TABLE CFG_SYSTEM_PARAMETERS
  (
    ID          NUMBER (10) NOT NULL ,
    VERSION     NUMBER (10) NOT NULL ,
    INSERT_TIME DATE DEFAULT sysdate NOT NULL ,
    UPDATE_TIME DATE NOT NULL ,
    PARAM_CODE  VARCHAR2 (80 BYTE) ,
    PARAM_VALUE VARCHAR2 (255 BYTE) ,
    DESCRIPTION VARCHAR2 (255 BYTE)
  ) ;
COMMENT ON COLUMN CFG_SYSTEM_PARAMETERS.ID
IS
  'System parameter ID' ;
  COMMENT ON COLUMN CFG_SYSTEM_PARAMETERS.VERSION
IS
  'System parameter version' ;
  COMMENT ON COLUMN CFG_SYSTEM_PARAMETERS.INSERT_TIME
IS
  'System parameter insert time' ;
  COMMENT ON COLUMN CFG_SYSTEM_PARAMETERS.UPDATE_TIME
IS
  'System parameter update time' ;
  COMMENT ON COLUMN CFG_SYSTEM_PARAMETERS.PARAM_CODE
IS
  'System parameter code' ;
  COMMENT ON COLUMN CFG_SYSTEM_PARAMETERS.PARAM_VALUE
IS
  'System parameter value' ;
  COMMENT ON COLUMN CFG_SYSTEM_PARAMETERS.DESCRIPTION
IS
  'System parameter description' ;
  ALTER TABLE CFG_SYSTEM_PARAMETERS ADD CONSTRAINT CFG_SYSTEM_PARAMETERS_PK PRIMARY KEY ( ID ) ;

CREATE TABLE CTX_ATTACHMENTS
  (
    ID          NUMBER (10) NOT NULL ,
    VERSION     NUMBER (10) NOT NULL ,
    INSERT_TIME DATE DEFAULT sysdate NOT NULL ,
    UPDATE_TIME DATE NOT NULL ,
    FILENAME    VARCHAR2 (255 BYTE) NOT NULL ,
    DESCRIPTION VARCHAR2 (255 BYTE) ,
    MIMETYPE    VARCHAR2 (50 BYTE) NOT NULL ,
    DATA BLOB NOT NULL ,
    TYPE        VARCHAR2 (50 BYTE) NOT NULL ,
    FILESIZE    NUMBER (10) NOT NULL ,
    REF_CONTEXT NUMBER (10)
  ) ;
COMMENT ON COLUMN CTX_ATTACHMENTS.ID
IS
  'Context attachment ID' ;
  COMMENT ON COLUMN CTX_ATTACHMENTS.VERSION
IS
  'Context attachment version' ;
  COMMENT ON COLUMN CTX_ATTACHMENTS.INSERT_TIME
IS
  'Context attachment insert time' ;
  COMMENT ON COLUMN CTX_ATTACHMENTS.UPDATE_TIME
IS
  'Context attachment update time' ;
  COMMENT ON COLUMN CTX_ATTACHMENTS.FILENAME
IS
  'Context attachment filename' ;
  COMMENT ON COLUMN CTX_ATTACHMENTS.DESCRIPTION
IS
  'Context attachment description' ;
  COMMENT ON COLUMN CTX_ATTACHMENTS.MIMETYPE
IS
  'Context attachment mimetype' ;
  COMMENT ON COLUMN CTX_ATTACHMENTS.DATA
IS
  'Attachment data' ;
  COMMENT ON COLUMN CTX_ATTACHMENTS.TYPE
IS
  'Attachment type' ;
  COMMENT ON COLUMN CTX_ATTACHMENTS.FILESIZE
IS
  'Context attachment file size' ;
  COMMENT ON COLUMN CTX_ATTACHMENTS.REF_CONTEXT
IS
  'Context reference' ;
  ALTER TABLE CTX_ATTACHMENTS ADD CONSTRAINT CTX_ATTACHMENTS_PK PRIMARY KEY ( ID ) ;

CREATE TABLE CTX_ATTACHMENT_TYPES
  (
    ID          NUMBER (10) NOT NULL ,
    VERSION     NUMBER (10) NOT NULL ,
    INSERT_TIME DATE DEFAULT sysdate NOT NULL ,
    UPDATE_TIME DATE NOT NULL ,
    CODE        VARCHAR2 (50 BYTE) NOT NULL ,
    DESCRIPTION VARCHAR2 (255 BYTE) NOT NULL
  ) ;
COMMENT ON COLUMN CTX_ATTACHMENT_TYPES.ID
IS
  'Context attachment type ID' ;
  COMMENT ON COLUMN CTX_ATTACHMENT_TYPES.VERSION
IS
  'Context attachment type version' ;
  COMMENT ON COLUMN CTX_ATTACHMENT_TYPES.INSERT_TIME
IS
  'Context attachment type insert time' ;
  COMMENT ON COLUMN CTX_ATTACHMENT_TYPES.UPDATE_TIME
IS
  'Context attachment type update time' ;
  COMMENT ON COLUMN CTX_ATTACHMENT_TYPES.CODE
IS
  'Context attachment type code' ;
  COMMENT ON COLUMN CTX_ATTACHMENT_TYPES.DESCRIPTION
IS
  'Context attachment type description' ;
  ALTER TABLE CTX_ATTACHMENT_TYPES ADD CONSTRAINT CTX_ATTACHMENT_TYPES_PK PRIMARY KEY ( ID ) ;
  ALTER TABLE CTX_ATTACHMENT_TYPES ADD CONSTRAINT ATTACHMENT_TYPE_UN UNIQUE ( CODE ) ;

CREATE TABLE CTX_CONTEXTS
  (
    ID          NUMBER (10) NOT NULL ,
    VERSION     NUMBER (10) NOT NULL ,
    INSERT_TIME DATE DEFAULT sysdate NOT NULL ,
    UPDATE_TIME DATE NOT NULL ,
    CLASS_NAME  VARCHAR2 (255 BYTE) NOT NULL
  ) ;
COMMENT ON COLUMN CTX_CONTEXTS.ID
IS
  'Context ID' ;
  COMMENT ON COLUMN CTX_CONTEXTS.VERSION
IS
  'Context version' ;
  COMMENT ON COLUMN CTX_CONTEXTS.INSERT_TIME
IS
  'Context insert time' ;
  COMMENT ON COLUMN CTX_CONTEXTS.UPDATE_TIME
IS
  'Context update time' ;
  COMMENT ON COLUMN CTX_CONTEXTS.CLASS_NAME
IS
  'Context class name' ;
  ALTER TABLE CTX_CONTEXTS ADD CONSTRAINT CTX_CONTEXTS_PK PRIMARY KEY ( ID ) ;

CREATE TABLE DRW_FLOORS
  (
    ID          NUMBER (10) NOT NULL ,
    VERSION     NUMBER (10) NOT NULL ,
    INSERT_TIME DATE DEFAULT sysdate NOT NULL ,
    UPDATE_TIME DATE NOT NULL ,
    NAME        VARCHAR2 (100 BYTE) ,
    DESCRIPTION VARCHAR2 (255 BYTE) ,
    "ORDER"     NUMBER ,
    WIDTH FLOAT ,
    HEIGHT FLOAT ,
    REF_CONTEXT      NUMBER (10) NOT NULL ,
    REF_ORGANIZATION NUMBER (10) NOT NULL
  ) ;
COMMENT ON COLUMN DRW_FLOORS.ID
IS
  'Organization parameter ID' ;
  COMMENT ON COLUMN DRW_FLOORS.VERSION
IS
  'Organization parameter version' ;
  COMMENT ON COLUMN DRW_FLOORS.INSERT_TIME
IS
  'Organization parameter insert time' ;
  COMMENT ON COLUMN DRW_FLOORS.UPDATE_TIME
IS
  'Organization parameter update time' ;
  COMMENT ON COLUMN DRW_FLOORS.NAME
IS
  'Organization parameter code' ;
  COMMENT ON COLUMN DRW_FLOORS.DESCRIPTION
IS
  'Organization parameter description' ;
CREATE UNIQUE INDEX DRW_FLOORS__IDX ON DRW_FLOORS
  (
    REF_CONTEXT ASC
  )
  ;
  ALTER TABLE DRW_FLOORS ADD CONSTRAINT DRW_FLOORS_PK PRIMARY KEY ( ID ) ;

CREATE TABLE DRW_SHAPES
  (
    ID          NUMBER (10) NOT NULL ,
    VERSION     NUMBER (10) NOT NULL ,
    INSERT_TIME DATE DEFAULT sysdate NOT NULL ,
    UPDATE_TIME DATE NOT NULL ,
    TYPE        VARCHAR2 (20 BYTE) ,
    START_X FLOAT ,
    START_Y FLOAT ,
    SIZE_X FLOAT ,
    SIZE_Y FLOAT ,
    RADIUS FLOAT ,
    "ORDER" NUMBER
  ) ;
COMMENT ON COLUMN DRW_SHAPES.ID
IS
  'Organization parameter ID' ;
  COMMENT ON COLUMN DRW_SHAPES.VERSION
IS
  'Organization parameter version' ;
  COMMENT ON COLUMN DRW_SHAPES.INSERT_TIME
IS
  'Organization parameter insert time' ;
  COMMENT ON COLUMN DRW_SHAPES.UPDATE_TIME
IS
  'Organization parameter update time' ;
  COMMENT ON COLUMN DRW_SHAPES.TYPE
IS
  'Organization parameter code' ;
  COMMENT ON COLUMN DRW_SHAPES.START_X
IS
  'Organization parameter description' ;
  ALTER TABLE DRW_SHAPES ADD CONSTRAINT DRW_SHAPES_PK PRIMARY KEY ( ID ) ;

CREATE TABLE EQP_EQUIPMENTS
  (
    ID                            NUMBER (10) NOT NULL ,
    VERSION                       NUMBER (10) NOT NULL ,
    INSERT_TIME                   DATE DEFAULT sysdate NOT NULL ,
    UPDATE_TIME                   DATE NOT NULL ,
    NAME                          VARCHAR2 (100 BYTE) ,
    DESCRIPTION                   VARCHAR2 (255 BYTE) ,
    REF_EQUIPMENTS_EQUIPMENTTYPES NUMBER (10) NOT NULL
  ) ;
COMMENT ON COLUMN EQP_EQUIPMENTS.ID
IS
  'Organization parameter ID' ;
  COMMENT ON COLUMN EQP_EQUIPMENTS.VERSION
IS
  'Organization parameter version' ;
  COMMENT ON COLUMN EQP_EQUIPMENTS.INSERT_TIME
IS
  'Organization parameter insert time' ;
  COMMENT ON COLUMN EQP_EQUIPMENTS.UPDATE_TIME
IS
  'Organization parameter update time' ;
  COMMENT ON COLUMN EQP_EQUIPMENTS.NAME
IS
  'Organization parameter code' ;
  COMMENT ON COLUMN EQP_EQUIPMENTS.DESCRIPTION
IS
  'Organization parameter description' ;
  ALTER TABLE EQP_EQUIPMENTS ADD CONSTRAINT EQP_EQUIPMENTS_PK PRIMARY KEY ( ID, REF_EQUIPMENTS_EQUIPMENTTYPES ) ;

CREATE TABLE EQP_EQUIPMENTTYPES
  (
    ID               NUMBER (10) NOT NULL ,
    VERSION          NUMBER (10) NOT NULL ,
    INSERT_TIME      DATE DEFAULT sysdate NOT NULL ,
    UPDATE_TIME      DATE NOT NULL ,
    NAME             VARCHAR2 (100 BYTE) ,
    DESCRIPTION      VARCHAR2 (255 BYTE) ,
    REF_ORGANIZATION NUMBER (10) NOT NULL
  ) ;
COMMENT ON COLUMN EQP_EQUIPMENTTYPES.ID
IS
  'Organization parameter ID' ;
  COMMENT ON COLUMN EQP_EQUIPMENTTYPES.VERSION
IS
  'Organization parameter version' ;
  COMMENT ON COLUMN EQP_EQUIPMENTTYPES.INSERT_TIME
IS
  'Organization parameter insert time' ;
  COMMENT ON COLUMN EQP_EQUIPMENTTYPES.UPDATE_TIME
IS
  'Organization parameter update time' ;
  COMMENT ON COLUMN EQP_EQUIPMENTTYPES.NAME
IS
  'Organization parameter code' ;
  COMMENT ON COLUMN EQP_EQUIPMENTTYPES.DESCRIPTION
IS
  'Organization parameter description' ;
  ALTER TABLE EQP_EQUIPMENTTYPES ADD CONSTRAINT EQP_EQUIPMENTTYPES_PK PRIMARY KEY ( ID ) ;

CREATE TABLE ORG_ORGANIZATIONS
  (
    ID               NUMBER (10) NOT NULL ,
    VERSION          NUMBER (10) NOT NULL ,
    INSERT_TIME      DATE DEFAULT sysdate NOT NULL ,
    UPDATE_TIME      DATE NOT NULL ,
    NAME             VARCHAR2 (80 BYTE) NOT NULL ,
    VAT_NUMBER       VARCHAR2 (50 BYTE) NOT NULL ,
    LEGAL_RESIDENCE  VARCHAR2 (80 BYTE) NOT NULL ,
    EMAIL            VARCHAR2 (80 BYTE) NOT NULL ,
    PHONE            VARCHAR2 (30 BYTE) NOT NULL ,
    STATUS           VARCHAR2 (50 BYTE) ,
    REF_ORGANIZATION NUMBER (10) NOT NULL
  ) ;
COMMENT ON COLUMN ORG_ORGANIZATIONS.ID
IS
  'Organization ID' ;
  COMMENT ON COLUMN ORG_ORGANIZATIONS.VERSION
IS
  'Organization version user for optimistic lock' ;
  COMMENT ON COLUMN ORG_ORGANIZATIONS.INSERT_TIME
IS
  'Organization insert time' ;
  COMMENT ON COLUMN ORG_ORGANIZATIONS.UPDATE_TIME
IS
  'Organization update time' ;
  COMMENT ON COLUMN ORG_ORGANIZATIONS.NAME
IS
  'Organization name' ;
  COMMENT ON COLUMN ORG_ORGANIZATIONS.VAT_NUMBER
IS
  'Organization VAT number' ;
  COMMENT ON COLUMN ORG_ORGANIZATIONS.LEGAL_RESIDENCE
IS
  'Organization legal residence' ;
  COMMENT ON COLUMN ORG_ORGANIZATIONS.EMAIL
IS
  'Organization email' ;
  COMMENT ON COLUMN ORG_ORGANIZATIONS.PHONE
IS
  'Organization phone number' ;
  COMMENT ON COLUMN ORG_ORGANIZATIONS.STATUS
IS
  'Organization status' ;
  ALTER TABLE ORG_ORGANIZATIONS ADD CONSTRAINT ORG_ORGANIZATIONS_PK PRIMARY KEY ( ID ) ;

CREATE TABLE PRP_AIRCONDITIONING
  (
    ID                        NUMBER (10) NOT NULL ,
    VERSION                   NUMBER (10) NOT NULL ,
    INSERT_TIME               DATE DEFAULT sysdate NOT NULL ,
    UPDATE_TIME               DATE NOT NULL ,
    NAME                      VARCHAR2 (100 BYTE) ,
    DESCRIPTION               VARCHAR2 (255 BYTE) ,
    REF_PREREQUISITE_LAYOUTS  NUMBER (10) NOT NULL ,
    REF_PREREQUISITE_LAYOUTS1 NUMBER (10) NOT NULL ,
    REF_PREREQUISITE_LAYOUTS2 NUMBER (10) NOT NULL ,
    REF_DRAWING_SHAPES        NUMBER (10) NOT NULL
  ) ;
COMMENT ON COLUMN PRP_AIRCONDITIONING.ID
IS
  'Organization parameter ID' ;
  COMMENT ON COLUMN PRP_AIRCONDITIONING.VERSION
IS
  'Organization parameter version' ;
  COMMENT ON COLUMN PRP_AIRCONDITIONING.INSERT_TIME
IS
  'Organization parameter insert time' ;
  COMMENT ON COLUMN PRP_AIRCONDITIONING.UPDATE_TIME
IS
  'Organization parameter update time' ;
  COMMENT ON COLUMN PRP_AIRCONDITIONING.NAME
IS
  'Organization parameter code' ;
  COMMENT ON COLUMN PRP_AIRCONDITIONING.DESCRIPTION
IS
  'Organization parameter description' ;
CREATE UNIQUE INDEX PRP_AIRCONDITIONING__IDX ON PRP_AIRCONDITIONING
  (
    REF_DRAWING_SHAPES ASC
  )
  ;
  ALTER TABLE PRP_AIRCONDITIONING ADD CONSTRAINT PRP_AIRCONDITIONING_PK PRIMARY KEY ( ID ) ;

CREATE TABLE PRP_CLEANINGS
  (
    ID                        NUMBER (10) NOT NULL ,
    VERSION                   NUMBER (10) NOT NULL ,
    INSERT_TIME               DATE DEFAULT sysdate NOT NULL ,
    UPDATE_TIME               DATE NOT NULL ,
    NAME                      VARCHAR2 (100 BYTE) ,
    DESCRIPTION               VARCHAR2 (255 BYTE) ,
    REF_DRAWING_SHAPES        NUMBER (10) NOT NULL ,
    REF_PREREQUISITE_LAYOUTS  NUMBER (10) NOT NULL ,
    REF_PREREQUISITE_LAYOUTS1 NUMBER (10) NOT NULL ,
    REF_PREREQUISITE_LAYOUTS2 NUMBER (10) NOT NULL
  ) ;
COMMENT ON COLUMN PRP_CLEANINGS.ID
IS
  'Organization parameter ID' ;
  COMMENT ON COLUMN PRP_CLEANINGS.VERSION
IS
  'Organization parameter version' ;
  COMMENT ON COLUMN PRP_CLEANINGS.INSERT_TIME
IS
  'Organization parameter insert time' ;
  COMMENT ON COLUMN PRP_CLEANINGS.UPDATE_TIME
IS
  'Organization parameter update time' ;
  COMMENT ON COLUMN PRP_CLEANINGS.NAME
IS
  'Organization parameter code' ;
  COMMENT ON COLUMN PRP_CLEANINGS.DESCRIPTION
IS
  'Organization parameter description' ;
CREATE UNIQUE INDEX PRP_CLEANINGS__IDX ON PRP_CLEANINGS
  (
    REF_DRAWING_SHAPES ASC
  )
  ;
  ALTER TABLE PRP_CLEANINGS ADD CONSTRAINT PRP_CLEANINGS_PK PRIMARY KEY ( ID ) ;

CREATE TABLE PRP_EQUIPMENTS
  (
    ID                        NUMBER (10) NOT NULL ,
    VERSION                   NUMBER (10) NOT NULL ,
    INSERT_TIME               DATE DEFAULT sysdate NOT NULL ,
    UPDATE_TIME               DATE NOT NULL ,
    NAME                      VARCHAR2 (100 BYTE) ,
    DESCRIPTION               VARCHAR2 (255 BYTE) ,
    REF_EQUIPMENTS            NUMBER (10) NOT NULL ,
    REF_PREREQUISITE_LAYOUTS  NUMBER (10) NOT NULL ,
    REF_PREREQUISITE_LAYOUTS1 NUMBER (10) NOT NULL ,
    REF_PREREQUISITE_LAYOUTS2 NUMBER (10) NOT NULL ,
    REF_DRAWING_SHAPES        NUMBER (10) NOT NULL ,
    REF_EQUIPMENTS1           NUMBER (10) NOT NULL
  ) ;
COMMENT ON COLUMN PRP_EQUIPMENTS.ID
IS
  'Organization parameter ID' ;
  COMMENT ON COLUMN PRP_EQUIPMENTS.VERSION
IS
  'Organization parameter version' ;
  COMMENT ON COLUMN PRP_EQUIPMENTS.INSERT_TIME
IS
  'Organization parameter insert time' ;
  COMMENT ON COLUMN PRP_EQUIPMENTS.UPDATE_TIME
IS
  'Organization parameter update time' ;
  COMMENT ON COLUMN PRP_EQUIPMENTS.NAME
IS
  'Organization parameter code' ;
  COMMENT ON COLUMN PRP_EQUIPMENTS.DESCRIPTION
IS
  'Organization parameter description' ;
CREATE UNIQUE INDEX PRP_EQUIPMENTS__IDX ON PRP_EQUIPMENTS
  (
    REF_EQUIPMENTS ASC , REF_EQUIPMENTS1 ASC
  )
  ;
  ALTER TABLE PRP_EQUIPMENTS ADD CONSTRAINT PRP_EQUIPMENTS_PK PRIMARY KEY ( ID ) ;

CREATE TABLE PRP_LAYOUTS
  (
    ID                           NUMBER (10) NOT NULL ,
    VERSION                      NUMBER (10) NOT NULL ,
    INSERT_TIME                  DATE DEFAULT sysdate NOT NULL ,
    UPDATE_TIME                  DATE NOT NULL ,
    NAME                         VARCHAR2 (100 BYTE) ,
    DESCRIPTION                  VARCHAR2 (255 BYTE) ,
    REF_ORGANIZATION             NUMBER (10) NOT NULL ,
    REF_DRAWING_FLOORS           NUMBER (10) NOT NULL ,
    REF_DRAWING_SHAPES           NUMBER (10) NOT NULL ,
    REF_PREREQUISITE_RISKCLASSES NUMBER (10) NOT NULL
  ) ;
COMMENT ON COLUMN PRP_LAYOUTS.ID
IS
  'Organization parameter ID' ;
  COMMENT ON COLUMN PRP_LAYOUTS.VERSION
IS
  'Organization parameter version' ;
  COMMENT ON COLUMN PRP_LAYOUTS.INSERT_TIME
IS
  'Organization parameter insert time' ;
  COMMENT ON COLUMN PRP_LAYOUTS.UPDATE_TIME
IS
  'Organization parameter update time' ;
  COMMENT ON COLUMN PRP_LAYOUTS.NAME
IS
  'Organization parameter code' ;
  COMMENT ON COLUMN PRP_LAYOUTS.DESCRIPTION
IS
  'Organization parameter description' ;
CREATE UNIQUE INDEX PRP_LAYOUTS__IDX ON PRP_LAYOUTS
  (
    REF_PREREQUISITE_RISKCLASSES ASC
  )
  ;
CREATE UNIQUE INDEX PRP_LAYOUTS__IDXv1 ON PRP_LAYOUTS
  (
    REF_DRAWING_SHAPES ASC
  )
  ;
  ALTER TABLE PRP_LAYOUTS ADD CONSTRAINT PRP_LAYOUTS_PK PRIMARY KEY ( ID, REF_ORGANIZATION, REF_DRAWING_FLOORS ) ;

CREATE TABLE PRP_PESTCONTROLS
  (
    ID                        NUMBER (10) NOT NULL ,
    VERSION                   NUMBER (10) NOT NULL ,
    INSERT_TIME               DATE DEFAULT sysdate NOT NULL ,
    UPDATE_TIME               DATE NOT NULL ,
    NAME                      VARCHAR2 (100 BYTE) ,
    DESCRIPTION               VARCHAR2 (255 BYTE) ,
    REF_PREREQUISITE_LAYOUTS  NUMBER (10) NOT NULL ,
    REF_PREREQUISITE_LAYOUTS1 NUMBER (10) NOT NULL ,
    REF_PREREQUISITE_LAYOUTS2 NUMBER (10) NOT NULL ,
    REF_DRAWING_SHAPES        NUMBER (10) NOT NULL
  ) ;
COMMENT ON COLUMN PRP_PESTCONTROLS.ID
IS
  'Organization parameter ID' ;
  COMMENT ON COLUMN PRP_PESTCONTROLS.VERSION
IS
  'Organization parameter version' ;
  COMMENT ON COLUMN PRP_PESTCONTROLS.INSERT_TIME
IS
  'Organization parameter insert time' ;
  COMMENT ON COLUMN PRP_PESTCONTROLS.UPDATE_TIME
IS
  'Organization parameter update time' ;
  COMMENT ON COLUMN PRP_PESTCONTROLS.NAME
IS
  'Organization parameter code' ;
  COMMENT ON COLUMN PRP_PESTCONTROLS.DESCRIPTION
IS
  'Organization parameter description' ;
CREATE UNIQUE INDEX PRP_PESTCONTROLS__IDX ON PRP_PESTCONTROLS
  (
    REF_DRAWING_SHAPES ASC
  )
  ;
  ALTER TABLE PRP_PESTCONTROLS ADD CONSTRAINT PRP_PESTCONTROLS_PK PRIMARY KEY ( ID ) ;

CREATE TABLE PRP_RISKCLASSES
  (
    ID               NUMBER (10) NOT NULL ,
    VERSION          NUMBER (10) NOT NULL ,
    INSERT_TIME      DATE DEFAULT sysdate NOT NULL ,
    UPDATE_TIME      DATE NOT NULL ,
    NAME             VARCHAR2 (100 BYTE) ,
    DESCRIPTION      VARCHAR2 (255 BYTE) ,
    COLOR            VARCHAR2 (20) ,
    REF_ORGANIZATION NUMBER (10) NOT NULL
  ) ;
COMMENT ON COLUMN PRP_RISKCLASSES.ID
IS
  'Organization parameter ID' ;
  COMMENT ON COLUMN PRP_RISKCLASSES.VERSION
IS
  'Organization parameter version' ;
  COMMENT ON COLUMN PRP_RISKCLASSES.INSERT_TIME
IS
  'Organization parameter insert time' ;
  COMMENT ON COLUMN PRP_RISKCLASSES.UPDATE_TIME
IS
  'Organization parameter update time' ;
  COMMENT ON COLUMN PRP_RISKCLASSES.NAME
IS
  'Organization parameter code' ;
  COMMENT ON COLUMN PRP_RISKCLASSES.DESCRIPTION
IS
  'Organization parameter description' ;
  COMMENT ON COLUMN PRP_RISKCLASSES.REF_ORGANIZATION
IS
  'Organization reference' ;
  ALTER TABLE PRP_RISKCLASSES ADD CONSTRAINT PRP_RISKCLASSES_PK PRIMARY KEY ( ID ) ;

CREATE TABLE PRP_WASTEDISPOSALS
  (
    ID                        NUMBER (10) NOT NULL ,
    VERSION                   NUMBER (10) NOT NULL ,
    INSERT_TIME               DATE DEFAULT sysdate NOT NULL ,
    UPDATE_TIME               DATE NOT NULL ,
    NAME                      VARCHAR2 (100 BYTE) ,
    DESCRIPTION               VARCHAR2 (255 BYTE) ,
    REF_DRAWING_SHAPES        NUMBER (10) NOT NULL ,
    REF_PREREQUISITE_LAYOUTS  NUMBER (10) NOT NULL ,
    REF_PREREQUISITE_LAYOUTS1 NUMBER (10) NOT NULL ,
    REF_PREREQUISITE_LAYOUTS2 NUMBER (10) NOT NULL
  ) ;
COMMENT ON COLUMN PRP_WASTEDISPOSALS.ID
IS
  'Organization parameter ID' ;
  COMMENT ON COLUMN PRP_WASTEDISPOSALS.VERSION
IS
  'Organization parameter version' ;
  COMMENT ON COLUMN PRP_WASTEDISPOSALS.INSERT_TIME
IS
  'Organization parameter insert time' ;
  COMMENT ON COLUMN PRP_WASTEDISPOSALS.UPDATE_TIME
IS
  'Organization parameter update time' ;
  COMMENT ON COLUMN PRP_WASTEDISPOSALS.NAME
IS
  'Organization parameter code' ;
  COMMENT ON COLUMN PRP_WASTEDISPOSALS.DESCRIPTION
IS
  'Organization parameter description' ;
CREATE UNIQUE INDEX PRP_WASTEDISPOSALS__IDX ON PRP_WASTEDISPOSALS
  (
    REF_DRAWING_SHAPES ASC
  )
  ;
  ALTER TABLE PRP_WASTEDISPOSALS ADD CONSTRAINT PRP_WASTEDISPOSALS_PK PRIMARY KEY ( ID, REF_PREREQUISITE_LAYOUTS, REF_PREREQUISITE_LAYOUTS1, REF_PREREQUISITE_LAYOUTS2 ) ;

CREATE TABLE PRP_WATERSUPPLIES
  (
    ID                        NUMBER (10) NOT NULL ,
    VERSION                   NUMBER (10) NOT NULL ,
    INSERT_TIME               DATE DEFAULT sysdate NOT NULL ,
    UPDATE_TIME               DATE NOT NULL ,
    NAME                      VARCHAR2 (100 BYTE) ,
    DESCRIPTION               VARCHAR2 (255 BYTE) ,
    REF_PREREQUISITE_LAYOUTS  NUMBER (10) NOT NULL ,
    REF_DRAWING_SHAPES        NUMBER (10) NOT NULL ,
    REF_PREREQUISITE_LAYOUTS1 NUMBER (10) NOT NULL ,
    REF_PREREQUISITE_LAYOUTS2 NUMBER (10) NOT NULL
  ) ;
COMMENT ON COLUMN PRP_WATERSUPPLIES.ID
IS
  'Organization parameter ID' ;
  COMMENT ON COLUMN PRP_WATERSUPPLIES.VERSION
IS
  'Organization parameter version' ;
  COMMENT ON COLUMN PRP_WATERSUPPLIES.INSERT_TIME
IS
  'Organization parameter insert time' ;
  COMMENT ON COLUMN PRP_WATERSUPPLIES.UPDATE_TIME
IS
  'Organization parameter update time' ;
  COMMENT ON COLUMN PRP_WATERSUPPLIES.NAME
IS
  'Organization parameter code' ;
  COMMENT ON COLUMN PRP_WATERSUPPLIES.DESCRIPTION
IS
  'Organization parameter description' ;
CREATE UNIQUE INDEX PRP_WATERSUPPLIES__IDX ON PRP_WATERSUPPLIES
  (
    REF_DRAWING_SHAPES ASC
  )
  ;
  ALTER TABLE PRP_WATERSUPPLIES ADD CONSTRAINT PRP_WATERSUPPLIES_PK PRIMARY KEY ( ID ) ;

CREATE TABLE ROL_PROFILES
  (
    ID          NUMBER (10) NOT NULL ,
    INSERT_TIME TIMESTAMP NOT NULL ,
    UPDATE_TIME TIMESTAMP NOT NULL ,
    VERSION     NUMBER (10) ,
    NAME        VARCHAR2 (4000) NOT NULL
  ) ;
ALTER TABLE ROL_PROFILES ADD CONSTRAINT ROL_PROFILES_PK PRIMARY KEY ( ID ) ;

CREATE TABLE ROL_ROLES
  (
    ID               NUMBER (10) NOT NULL ,
    INSERT_TIME      TIMESTAMP NOT NULL ,
    UPDATE_TIME      TIMESTAMP NOT NULL ,
    VERSION          NUMBER (10) ,
    NAME             VARCHAR2 (4000) NOT NULL ,
    DESCRIPTION      VARCHAR2 (200) ,
    REF_ORGANIZATION NUMBER (10)
  ) ;
ALTER TABLE ROL_ROLES ADD CONSTRAINT ROL_ROLES_PK PRIMARY KEY ( ID ) ;

CREATE TABLE ROL_USERS
  (
    ID                   NUMBER (10) NOT NULL ,
    VERSION              NUMBER (10) NOT NULL ,
    INSERT_TIME          DATE DEFAULT sysdate NOT NULL ,
    UPDATE_TIME          DATE NOT NULL ,
    FIRSTNAME            VARCHAR2 (80 BYTE) NOT NULL ,
    LASTNAME             VARCHAR2 (80 BYTE) NOT NULL ,
    USERNAME             VARCHAR2 (80 BYTE) NOT NULL ,
    PASSWORD             VARCHAR2 (80 BYTE) NOT NULL ,
    PASSWORD_EXPIRE_DATE DATE ,
    EMAIL                VARCHAR2 (80 BYTE) ,
    PHONE                VARCHAR2 (30 BYTE) ,
    STATUS               VARCHAR2 (50 BYTE) DEFAULT 'VALID' ,
    LANGUAGE             VARCHAR2 (20) ,
    REF_ORGANIZATION     NUMBER (10) NOT NULL ,
    REF_ROL_ROLES        NUMBER (10) NOT NULL
  ) ;
COMMENT ON COLUMN ROL_USERS.ID
IS
  'User ID' ;
  COMMENT ON COLUMN ROL_USERS.VERSION
IS
  'User version used for optimistic lock' ;
  COMMENT ON COLUMN ROL_USERS.INSERT_TIME
IS
  'User insert time' ;
  COMMENT ON COLUMN ROL_USERS.UPDATE_TIME
IS
  'User update time' ;
  COMMENT ON COLUMN ROL_USERS.FIRSTNAME
IS
  'User firstname' ;
  COMMENT ON COLUMN ROL_USERS.LASTNAME
IS
  'User last name' ;
  COMMENT ON COLUMN ROL_USERS.USERNAME
IS
  'Username' ;
  COMMENT ON COLUMN ROL_USERS.PASSWORD
IS
  'User password' ;
  COMMENT ON COLUMN ROL_USERS.PASSWORD_EXPIRE_DATE
IS
  'User password expire date' ;
  COMMENT ON COLUMN ROL_USERS.EMAIL
IS
  'User email' ;
  COMMENT ON COLUMN ROL_USERS.PHONE
IS
  'User phone' ;
  COMMENT ON COLUMN ROL_USERS.STATUS
IS
  'User status' ;
  COMMENT ON COLUMN ROL_USERS.REF_ORGANIZATION
IS
  'Organization reference' ;
  ALTER TABLE ROL_USERS ADD CONSTRAINT ROL_USERS_PK PRIMARY KEY ( ID ) ;
  ALTER TABLE ROL_USERS ADD CONSTRAINT USER_UN UNIQUE ( USERNAME ) ;

CREATE TABLE ROL_USERS_ROL_PROFILES
  (
    REF_ROL_ROLES    NUMBER (10) NOT NULL ,
    REF_ROL_PROFILES NUMBER (10) NOT NULL
  )
  TABLESPACE TABLESPACE_DATA ;
ALTER TABLE ROL_USERS_ROL_PROFILES ADD CONSTRAINT ROL_USERS_ROL_PROFILES__IDX PRIMARY KEY ( REF_ROL_ROLES, REF_ROL_PROFILES ) ;

CREATE TABLE ROL_USER_RIGHTS
  (
    REF_ROL_PROFILES NUMBER (10) NOT NULL ,
    insert_time      TIMESTAMP NOT NULL ,
    update_time      TIMESTAMP NOT NULL ,
    version          NUMBER (10) ,
    NAME             VARCHAR2 (50)
  ) ;
ALTER TABLE ROL_USER_RIGHTS ADD CONSTRAINT ROL_USER_RIGHTS_PK PRIMARY KEY ( REF_ROL_PROFILES ) ;

ALTER TABLE CFG_EMAIL_PARAMETERS ADD CONSTRAINT CFG_EML_PARMS_CFG_EML_TMPLS_FK FOREIGN KEY ( REF_EMAIL_TEMPLATE ) REFERENCES CFG_EMAIL_TEMPLATES ( ID ) ;

ALTER TABLE CFG_ORGANIZATION_PARAMETERS ADD CONSTRAINT CFG_ORGA_PARAMS_ORG_ORGAS_FK FOREIGN KEY ( REF_ORGANIZATION ) REFERENCES ORG_ORGANIZATIONS ( ID ) ;

ALTER TABLE CTX_ATTACHMENTS ADD CONSTRAINT CTX_ATTACHS_CTX_CONTEXTS_FK FOREIGN KEY ( REF_CONTEXT ) REFERENCES CTX_CONTEXTS ( ID ) ;

ALTER TABLE ROL_USERS_ROL_PROFILES ADD CONSTRAINT FK_ASS_7 FOREIGN KEY ( REF_ROL_ROLES ) REFERENCES ROL_ROLES ( ID ) ;

ALTER TABLE ROL_USERS_ROL_PROFILES ADD CONSTRAINT FK_ASS_8 FOREIGN KEY ( REF_ROL_PROFILES ) REFERENCES ROL_PROFILES ( ID ) ;

ALTER TABLE ROL_USERS ADD CONSTRAINT REF_ROLE FOREIGN KEY ( REF_ROL_ROLES ) REFERENCES ROL_ROLES ( ID ) ;

ALTER TABLE ROL_ROLES ADD CONSTRAINT ROL_ORGS_ROL_ROLES FOREIGN KEY ( REF_ORGANIZATION ) REFERENCES ORG_ORGANIZATIONS ( ID ) ;

ALTER TABLE ROL_USERS ADD CONSTRAINT ROL_USERS_ORG_ORGAS_FK FOREIGN KEY ( REF_ORGANIZATION ) REFERENCES ORG_ORGANIZATIONS ( ID ) ;

ALTER TABLE ORG_ORGANIZATIONS ADD CONSTRAINT Relation_270 FOREIGN KEY ( REF_ORGANIZATION ) REFERENCES ORG_ORGANIZATIONS ( ID ) ;

ALTER TABLE PRP_LAYOUTS ADD CONSTRAINT Relation_276 FOREIGN KEY ( REF_PREREQUISITE_RISKCLASSES ) REFERENCES PRP_RISKCLASSES ( ID ) ;

ALTER TABLE DRW_FLOORS ADD CONSTRAINT Relation_278 FOREIGN KEY ( REF_CONTEXT ) REFERENCES CTX_CONTEXTS ( ID ) ;

ALTER TABLE PRP_LAYOUTS ADD CONSTRAINT Relation_281 FOREIGN KEY ( REF_ORGANIZATION ) REFERENCES ORG_ORGANIZATIONS ( ID ) ;

ALTER TABLE DRW_FLOORS ADD CONSTRAINT Relation_282 FOREIGN KEY ( REF_ORGANIZATION ) REFERENCES ORG_ORGANIZATIONS ( ID ) ;

ALTER TABLE PRP_LAYOUTS ADD CONSTRAINT Relation_283 FOREIGN KEY ( REF_DRAWING_FLOORS ) REFERENCES DRW_FLOORS ( ID ) ;

ALTER TABLE PRP_WATERSUPPLIES ADD CONSTRAINT Relation_285 FOREIGN KEY ( REF_PREREQUISITE_LAYOUTS, REF_PREREQUISITE_LAYOUTS1, REF_PREREQUISITE_LAYOUTS2 ) REFERENCES PRP_LAYOUTS ( ID, REF_ORGANIZATION, REF_DRAWING_FLOORS ) ;

ALTER TABLE PRP_LAYOUTS ADD CONSTRAINT Relation_287 FOREIGN KEY ( REF_DRAWING_SHAPES ) REFERENCES DRW_SHAPES ( ID ) ;

ALTER TABLE PRP_WATERSUPPLIES ADD CONSTRAINT Relation_288 FOREIGN KEY ( REF_DRAWING_SHAPES ) REFERENCES DRW_SHAPES ( ID ) ;

ALTER TABLE PRP_AIRCONDITIONING ADD CONSTRAINT Relation_290 FOREIGN KEY ( REF_PREREQUISITE_LAYOUTS, REF_PREREQUISITE_LAYOUTS1, REF_PREREQUISITE_LAYOUTS2 ) REFERENCES PRP_LAYOUTS ( ID, REF_ORGANIZATION, REF_DRAWING_FLOORS ) ;

ALTER TABLE PRP_AIRCONDITIONING ADD CONSTRAINT Relation_291 FOREIGN KEY ( REF_DRAWING_SHAPES ) REFERENCES DRW_SHAPES ( ID ) ;

ALTER TABLE PRP_WASTEDISPOSALS ADD CONSTRAINT Relation_292 FOREIGN KEY ( REF_DRAWING_SHAPES ) REFERENCES DRW_SHAPES ( ID ) ;

ALTER TABLE PRP_WASTEDISPOSALS ADD CONSTRAINT Relation_293 FOREIGN KEY ( REF_PREREQUISITE_LAYOUTS, REF_PREREQUISITE_LAYOUTS1, REF_PREREQUISITE_LAYOUTS2 ) REFERENCES PRP_LAYOUTS ( ID, REF_ORGANIZATION, REF_DRAWING_FLOORS ) ;

ALTER TABLE PRP_CLEANINGS ADD CONSTRAINT Relation_294 FOREIGN KEY ( REF_DRAWING_SHAPES ) REFERENCES DRW_SHAPES ( ID ) ;

ALTER TABLE PRP_CLEANINGS ADD CONSTRAINT Relation_295 FOREIGN KEY ( REF_PREREQUISITE_LAYOUTS, REF_PREREQUISITE_LAYOUTS1, REF_PREREQUISITE_LAYOUTS2 ) REFERENCES PRP_LAYOUTS ( ID, REF_ORGANIZATION, REF_DRAWING_FLOORS ) ;

ALTER TABLE EQP_EQUIPMENTS ADD CONSTRAINT Relation_298 FOREIGN KEY ( REF_EQUIPMENTS_EQUIPMENTTYPES ) REFERENCES EQP_EQUIPMENTTYPES ( ID ) ;

ALTER TABLE PRP_EQUIPMENTS ADD CONSTRAINT Relation_299 FOREIGN KEY ( REF_EQUIPMENTS, REF_EQUIPMENTS1 ) REFERENCES EQP_EQUIPMENTS ( ID, REF_EQUIPMENTS_EQUIPMENTTYPES ) ;

ALTER TABLE PRP_EQUIPMENTS ADD CONSTRAINT Relation_300 FOREIGN KEY ( REF_PREREQUISITE_LAYOUTS, REF_PREREQUISITE_LAYOUTS1, REF_PREREQUISITE_LAYOUTS2 ) REFERENCES PRP_LAYOUTS ( ID, REF_ORGANIZATION, REF_DRAWING_FLOORS ) ;

ALTER TABLE PRP_EQUIPMENTS ADD CONSTRAINT Relation_301 FOREIGN KEY ( REF_DRAWING_SHAPES ) REFERENCES DRW_SHAPES ( ID ) ;

ALTER TABLE PRP_PESTCONTROLS ADD CONSTRAINT Relation_302 FOREIGN KEY ( REF_PREREQUISITE_LAYOUTS, REF_PREREQUISITE_LAYOUTS1, REF_PREREQUISITE_LAYOUTS2 ) REFERENCES PRP_LAYOUTS ( ID, REF_ORGANIZATION, REF_DRAWING_FLOORS ) ;

ALTER TABLE PRP_PESTCONTROLS ADD CONSTRAINT Relation_303 FOREIGN KEY ( REF_DRAWING_SHAPES ) REFERENCES DRW_SHAPES ( ID ) ;

ALTER TABLE EQP_EQUIPMENTTYPES ADD CONSTRAINT Relation_305 FOREIGN KEY ( REF_ORGANIZATION ) REFERENCES ORG_ORGANIZATIONS ( ID ) ;

ALTER TABLE ROL_USER_RIGHTS ADD CONSTRAINT fk_profiles_users_rights FOREIGN KEY ( REF_ROL_PROFILES ) REFERENCES ROL_PROFILES ( ID ) ;


-- Report sintetico di Oracle SQL Developer Data Modeler: 
-- 
-- CREATE TABLE                            25
-- CREATE INDEX                             9
-- ALTER TABLE                             58
-- CREATE VIEW                              0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
