******************************************************************************************************
 GPI s.p.a.

 SCRIPT DI MIGRATION 

 APPLICAZIONE: PrivacyManagement
 VERSIONE     
 CLIENTE      
 DATA         
 AUTORE       
 NOTE         

*******************************************************************************************************/

DEFINE _connectId = "[[CONNECT_IDENTIFIER]]"          		-- Oracle Net database alias
DEFINE _usrPrivacyManagement = "[[PRIVACYMGER_USR]]"        -- Utente Oracle PrivacyManagement
DEFINE _passwdPrivacyManagement = "[[PRIVACYMGER_PWD]]"     -- Password Oracle PrivacyManagement

DEFINE _usrIERepo = "[[IEREPO_USR]]"        -- Utente Oracle IE-REPOSITORY
DEFINE _passwdIERepo = "[[IEREPO_PWD]]"     -- Password Oracle IE-REPOSITORY


CONNECT &&_usrPrivacyManagement/&&_passwdPrivacyManagement@&&_connectId;


ALTER TABLE PRIVACY_DOCUMENTS ADD DOCUMENT_ID VARCHAR2 (256);


CONNECT &&_usrIERepo/&&_passwdIERepo@&&_connectId;

--- ADAPTER PRIVACY MANAGEMENT  ---
DECLARE 
	ADAPTER_ID NUMBER;
	OBJ_EXISTS NUMBER;
	CNT NUMBER;
BEGIN

   SELECT COUNT(*) INTO CNT
   FROM APPLICATIONS  WHERE EXTERNAL_CODE = 'PRIVACY_MANAGEMENT';
   IF CNT = 0 THEN
   
		SELECT SEQ_ADAPTERS.NEXTVAL INTO ADAPTER_ID FROM DUAL;
		INSERT INTO ADAPTERS (ID,DESCRIPTION) VALUES (ADAPTER_ID,'PRIVACY_MANAGEMENT');


		/* DECODE(A.MODALITY, 1->'CODE+DESCR', 2->'DESCR', 3->'CODE', 4->'VALUE', NULL) */
		INSERT INTO CLASSIFICATION_SCHEME_ADAP (ID,ID_CLASSIFICATION_SCHEME,ID_ADAPTER,ATTRIBUTE_CODE,ATTRIBUTE_LABEL,FL_VISIBILITY,ADAPTER_ORDER, MODALITY) VALUES (SEQ_CLASSIFICATION_SCHEME_ADAP.NEXTVAL,5,ADAPTER_ID,'soggettoCodice',NULL,0,NULL, 4);
		INSERT INTO CLASSIFICATION_SCHEME_ADAP (ID,ID_CLASSIFICATION_SCHEME,ID_ADAPTER,ATTRIBUTE_CODE,ATTRIBUTE_LABEL,FL_VISIBILITY,ADAPTER_ORDER, MODALITY) VALUES (SEQ_CLASSIFICATION_SCHEME_ADAP.NEXTVAL,8,ADAPTER_ID,'estensione','ICON',0,NULL, 3);
		INSERT INTO CLASSIFICATION_SCHEME_ADAP (ID,ID_CLASSIFICATION_SCHEME,ID_ADAPTER,ATTRIBUTE_CODE,ATTRIBUTE_LABEL,FL_VISIBILITY,ADAPTER_ORDER, MODALITY) VALUES (SEQ_CLASSIFICATION_SCHEME_ADAP.NEXTVAL,14,ADAPTER_ID,'dataDocumento','DATA DOC',0,NULL,1);
		INSERT INTO CLASSIFICATION_SCHEME_ADAP (ID,ID_CLASSIFICATION_SCHEME,ID_ADAPTER,ATTRIBUTE_CODE,ATTRIBUTE_LABEL,FL_VISIBILITY,ADAPTER_ORDER, MODALITY) VALUES (SEQ_CLASSIFICATION_SCHEME_ADAP.NEXTVAL,15,ADAPTER_ID,'versione','VERSIONE',0,NULL,4);
		INSERT INTO CLASSIFICATION_SCHEME_ADAP (ID,ID_CLASSIFICATION_SCHEME,ID_ADAPTER,ATTRIBUTE_CODE,ATTRIBUTE_LABEL,FL_VISIBILITY,ADAPTER_ORDER, MODALITY) VALUES (SEQ_CLASSIFICATION_SCHEME_ADAP.NEXTVAL,16,ADAPTER_ID,'tipoDocumento','TIPO DOCUMENTO',0,NULL,3);
		INSERT INTO CLASSIFICATION_SCHEME_ADAP (ID,ID_CLASSIFICATION_SCHEME,ID_ADAPTER,ATTRIBUTE_CODE,ATTRIBUTE_LABEL,FL_VISIBILITY,ADAPTER_ORDER, MODALITY) VALUES (SEQ_CLASSIFICATION_SCHEME_ADAP.NEXTVAL,19,ADAPTER_ID,'titoloDocumento','DOCUMENTO',0,NULL,4);
		INSERT INTO CLASSIFICATION_SCHEME_ADAP (ID,ID_CLASSIFICATION_SCHEME,ID_ADAPTER,ATTRIBUTE_CODE,ATTRIBUTE_LABEL,FL_VISIBILITY,ADAPTER_ORDER, MODALITY) VALUES (SEQ_CLASSIFICATION_SCHEME_ADAP.NEXTVAL,18,ADAPTER_ID,'nosologico',NULL,0,NULL,4);
		INSERT INTO CLASSIFICATION_SCHEME_ADAP (ID,ID_CLASSIFICATION_SCHEME,ID_ADAPTER,ATTRIBUTE_CODE,ATTRIBUTE_LABEL,FL_VISIBILITY,ADAPTER_ORDER,MODALITY) VALUES (SEQ_CLASSIFICATION_SCHEME_ADAP.NEXTVAL,38,ADAPTER_ID,'codRichiestaEsterna',null,0,null,4);
		INSERT INTO CLASSIFICATION_SCHEME_ADAP (ID,ID_CLASSIFICATION_SCHEME,ID_ADAPTER,ATTRIBUTE_CODE,ATTRIBUTE_LABEL,FL_VISIBILITY,ADAPTER_ORDER, MODALITY) VALUES (SEQ_CLASSIFICATION_SCHEME_ADAP.NEXTVAL,102,ADAPTER_ID,'codCartellaDea',NULL,0,NULL,4);


		SELECT COUNT(*) INTO OBJ_EXISTS FROM APPLICATIONS WHERE EXTERNAL_CODE = 'PRIVACY_MANAGEMENT';
		if (OBJ_EXISTS = 0) then
			execute immediate 
			'
				INSERT INTO APPLICATIONS (ID, EXTERNAL_CODE, DESCRIPTION, ID_ADAPTER_INBOUND, ID_ADAPTER_OUTBOUND)
					SELECT SEQ_APPLICATIONS.NEXTVAL, ''PRIVACY_MANAGEMENT'', ''PRIVACY MANAGEMENT'', '|| ADAPTER_ID ||', '|| ADAPTER_ID ||' FROM DUAL
			';
		end if;
	
	END IF;
		
	COMMIT;
END;
/
 
insert into dba_revisions(id, revision,description,script_name,INSERT_DATETIME) values (SEQ_DBA_REVISIONS.nextval, 22,'Aggiunta colonna DOCUMENT_ID sulla tabella PRIVACY_DOCUMENTS; aggiunta application PRIVACY_MANAGEMENT se non esiste SU IE-REPOSITORY ', 'wip.sql', sysdate);






