/******************************************************************************************************
 GPI s.p.a.

 SCRIPT DI MIGRATION 

 APPLICAZIONE: PrivacyManagement
 VERSIONE     
 CLIENTE      
 DATA         
 AUTORE       
 NOTE         

*******************************************************************************************************/

DEFINE _connectId = "[[CONNECT_IDENTIFIER]]"          		-- Oracle Net database alias
DEFINE _usrPrivacyManagement = "[[PRIVACYMGER_USR]]"        -- Utente Oracle PrivacyManagement
DEFINE _passwdPrivacyManagement = "[[PRIVACYMGER_PWD]]"     -- Password Oracle PrivacyManagement


CONNECT &&_usrPrivacyManagement/&&_passwdPrivacyManagement@&&_connectId;




--Task 592907 : I0013934 - APERTURA MODULO DI CONSENSO DA IE-OPERA

ALTER TABLE POLICY_CONTEXTS ADD    LOGO            VARCHAR2 (200) ;
ALTER TABLE POLICY_CONTEXTS ADD    TEMPLATE_REPORT VARCHAR2 (200);


CREATE TABLE PRIVACY_DOCUMENTS
  (
    ID            NUMBER (10) NOT NULL ,
    CREATION_DATE DATE ,
    DOCUMENT CLOB ,
    DOCUMENT_UPLOAD CLOB ,
    ID_PATIENT        NUMBER (10) NOT NULL ,
    ID_POLICY_CONTEXT NUMBER (10) NOT NULL
  ) ;
ALTER TABLE PRIVACY_DOCUMENTS ADD CONSTRAINT PRIVACY_DOCUMENTS_PK PRIMARY KEY ( ID ) ;

CREATE TABLE PRIVACY_DOC_PATIENT_CONS_REL
  (
    ID_PRIVACY_CONSENT  NUMBER (10) NOT NULL ,
    ID_PRIVACY_DOCUMENT NUMBER (10) NOT NULL
  ) ;
ALTER TABLE PRIVACY_DOC_PATIENT_CONS_REL ADD CONSTRAINT UN_PRIV_DOC_PAT_CONS_REL UNIQUE ( ID_PRIVACY_CONSENT , ID_PRIVACY_DOCUMENT ) ;


ALTER TABLE PRIVACY_DOCUMENTS ADD CONSTRAINT FK_PRIV_DOC_PATIENT FOREIGN KEY ( ID_PATIENT ) REFERENCES PATIENTS ( ID ) ;
ALTER TABLE PRIVACY_DOC_PATIENT_CONS_REL ADD CONSTRAINT FK_PRIV_DOC_PAT_CON_PRIV_CONS FOREIGN KEY ( ID_PRIVACY_CONSENT ) REFERENCES PATIENT_PRIVACY_CONSENTS ( ID ) ;
ALTER TABLE PRIVACY_DOC_PATIENT_CONS_REL ADD CONSTRAINT FK_PRIV_DOC_PAT_CON_PRIV_DOC FOREIGN KEY ( ID_PRIVACY_DOCUMENT ) REFERENCES PRIVACY_DOCUMENTS ( ID ) ;
ALTER TABLE PRIVACY_DOCUMENTS ADD CONSTRAINT FK_PRIV_DOC_POLICY_CTX FOREIGN KEY ( ID_POLICY_CONTEXT ) REFERENCES POLICY_CONTEXTS ( ID ) ;

CREATE SEQUENCE SEQ_PRIVACY_DOCUMENTS START WITH 1 MAXVALUE 999999999999999999999999999 MINVALUE 1 NOCYCLE NOCACHE NOORDER;


--Default columns
ALTER TABLE PRIVACY_DOCUMENTS ADD	CANCEL_DATETIME TIMESTAMP (6);
ALTER TABLE PRIVACY_DOCUMENTS ADD	CANCEL_USER VARCHAR2(255 CHAR); 
ALTER TABLE PRIVACY_DOCUMENTS ADD	DELETED NUMBER(1,0) DEFAULT 0 NOT NULL;
ALTER TABLE PRIVACY_DOCUMENTS ADD	INSERT_DATETIME TIMESTAMP (6);
ALTER TABLE PRIVACY_DOCUMENTS ADD	INSERT_USER VARCHAR2(255 CHAR);
ALTER TABLE PRIVACY_DOCUMENTS ADD	LASTUPDATE_DATETIME TIMESTAMP (6);
ALTER TABLE PRIVACY_DOCUMENTS ADD	LASTUPDATE_USER VARCHAR2(255 CHAR);
ALTER TABLE PRIVACY_DOCUMENTS ADD	ROW_VERSION NUMBER(19,0);


insert into dba_revisions(id, revision,description,script_name,insert_datetime) values (SEQ_DBA_REVISIONS.nextval, 5,'Aggiunta tabella PRIVACY_DOCUMENTS, PRIVACY_DOC_PATIENT_CONS_REL', 'wip.sql', sysdate);

ALTER TABLE POLICY_CONTEXTS ADD	FL_VISIBLE_TO_OPERATOR NUMBER (1) DEFAULT 0;
ALTER TABLE POLICY_CONTEXTS ADD CHECK ( FL_VISIBLE_TO_OPERATOR IN (0, 1));

update POLICY_CONTEXTS c set c.FL_VISIBLE_TO_OPERATOR=1;

insert into dba_revisions(id, revision,description,script_name,insert_datetime) values (SEQ_DBA_REVISIONS.nextval, 6,'Aggiunta colonna FL_VISIBLE_TO_OPERATOR sulla tabella POLICY_CONTEXTS', 'wip.sql', sysdate);

update PATIENT_PRIVACY_CONSENTS set deleted=0 where deleted is null;
update PATIENT_PRIV_CONS_SPECIFIC set deleted=0 where deleted is null;

ALTER TABLE PATIENT_PRIVACY_CONSENTS MODIFY DELETED NUMBER(1,0) DEFAULT 0 NOT NULL;
ALTER TABLE PATIENT_PRIV_CONS_SPECIFIC MODIFY DELETED NUMBER(1,0) DEFAULT 0 NOT NULL;


insert into dba_revisions(id, revision,description,script_name,insert_datetime) values (SEQ_DBA_REVISIONS.nextval, 7,'Set default deleted sulle tabelle PATIENT_PRIVACY_CONSENTS e PATIENT_PRIV_CONS_SPECIFIC', 'wip.sql', sysdate);


--R0014661 - GESTIONE MODELLI DI RACCOLTA CONSENSO  I0032222 - GESTIONE RACCOLTA DEL CONSENSO "IN QUALITA DI"

ALTER TABLE POLICY_CODING_SYSTEMS ADD FL_INCLUDE_IN_BPPC NUMBER (1) DEFAULT 0;
ALTER TABLE POLICY_CODING_SYSTEMS ADD CHECK ( FL_INCLUDE_IN_BPPC IN (0, 1));

--ADD type of answer per diversi tipi di risposta
ALTER TABLE POLICY_SET_LIST ADD TYPE_OF_ANSWER          VARCHAR2 (128);
ALTER TABLE POLICY_SET_LIST ADD PATTERN                 VARCHAR2 (200); 
ALTER TABLE POLICY_SET_LIST ADD STYLE_CSS            VARCHAR2 (200);

UPDATE POLICY_SET_LIST SET TYPE_OF_ANSWER='RADIO';

insert into dba_revisions(id, revision,description,script_name,insert_datetime) values (SEQ_DBA_REVISIONS.nextval, 8,'Gestione tipologia risposta associato al policy_set_list', 'wip.sql', sysdate);


ALTER TABLE PATIENT_PRIVACY_CONSENTS ADD ANSWER VARCHAR2 (4000);

insert into dba_revisions(id, revision,description,script_name,insert_datetime) values (SEQ_DBA_REVISIONS.nextval, 9,'Gestione inputtext policy_set_list', 'wip.sql', sysdate);


ALTER TABLE POLICY_SET_LIST ADD ORDER_BY NUMBER (10);

insert into dba_revisions(id, revision,description,script_name,insert_datetime) values (SEQ_DBA_REVISIONS.nextval, 10,'Aggiunta order_by per ordinamento policy_set_list', 'wip.sql', sysdate);


