/******************************************************************************************************
 GPI s.p.a.

 SCRIPT DI INSTALLAZIONE 

 APPLICAZIONE PRIVACY MANAGEMENT
 VERSIONE     ??.??
 CLIENTE      
 DATA         

 AUTORE       com.gpi.privacyManagement.util.InstallationScriptVerificator

 NOTE         Script generato automaticamente da SQLModeler e verificato a buildtime 

*******************************************************************************************************/



CREATE TABLE CFG_EMAIL_PARAMETERS
  (
    ID                 NUMBER (10) NOT NULL ,
    VERSION            NUMBER (10) NOT NULL ,
    INSERT_TIME        DATE DEFAULT sysdate NOT NULL ,
    UPDATE_TIME        DATE NOT NULL ,
    PARAM_CODE         VARCHAR2 (80 BYTE) NOT NULL ,
    PARAM_VALUE        VARCHAR2 (255 BYTE) NOT NULL ,
    DESCRIPTION        VARCHAR2 (255 BYTE) NOT NULL ,
    REF_EMAIL_TEMPLATE NUMBER (10) NOT NULL
  );

ALTER TABLE CFG_EMAIL_PARAMETERS ADD CONSTRAINT CFG_EMAIL_PARAMETERS_PK PRIMARY KEY ( ID );

CREATE TABLE CFG_EMAIL_TEMPLATES
  (
    ID          NUMBER (10) NOT NULL ,
    VERSION     NUMBER (10) NOT NULL ,
    INSERT_TIME DATE DEFAULT sysdate NOT NULL ,
    UPDATE_TIME DATE NOT NULL ,
    NAME        VARCHAR2 (80 BYTE) NOT NULL ,
    DESCRIPTION VARCHAR2 (255 BYTE) NOT NULL
  );

ALTER TABLE CFG_EMAIL_TEMPLATES ADD CONSTRAINT CFG_EMAIL_TEMPLATES_PK PRIMARY KEY ( ID );

CREATE TABLE CFG_ORGANIZATION_PARAMETERS
  (
    ID               NUMBER (10) NOT NULL ,
    VERSION          NUMBER (10) NOT NULL ,
    INSERT_TIME      DATE DEFAULT sysdate NOT NULL ,
    UPDATE_TIME      DATE NOT NULL ,
    PARAM_CODE       VARCHAR2 (80 BYTE) ,
    PARAM_VALUE      VARCHAR2 (255 BYTE) ,
    DESCRIPTION      VARCHAR2 (255 BYTE) ,
    REF_ORGANIZATION NUMBER (10) NOT NULL
  );

ALTER TABLE CFG_ORGANIZATION_PARAMETERS ADD CONSTRAINT CFG_ORGANIZATION_PARAMETERS_PK PRIMARY KEY ( ID );

CREATE TABLE CFG_SYSTEM_PARAMETERS
  (
    ID          NUMBER (10) NOT NULL ,
    VERSION     NUMBER (10) NOT NULL ,
    INSERT_TIME DATE DEFAULT sysdate NOT NULL ,
    UPDATE_TIME DATE NOT NULL ,
    PARAM_CODE  VARCHAR2 (80 BYTE) ,
    PARAM_VALUE VARCHAR2 (255 BYTE) ,
    DESCRIPTION VARCHAR2 (255 BYTE)
  );

ALTER TABLE CFG_SYSTEM_PARAMETERS ADD CONSTRAINT CFG_SYSTEM_PARAMETERS_PK PRIMARY KEY ( ID );

CREATE TABLE CTX_ATTACHMENTS
  (
    ID          NUMBER (10) NOT NULL ,
    VERSION     NUMBER (10) NOT NULL ,
    INSERT_TIME DATE DEFAULT sysdate NOT NULL ,
    UPDATE_TIME DATE NOT NULL ,
    FILENAME    VARCHAR2 (255 BYTE) NOT NULL ,
    DESCRIPTION VARCHAR2 (255 BYTE) ,
    MIMETYPE    VARCHAR2 (50 BYTE) NOT NULL ,
    DATA BLOB NOT NULL ,
    TYPE        VARCHAR2 (50 BYTE) NOT NULL ,
    FILESIZE    NUMBER (10) NOT NULL ,
    REF_CONTEXT NUMBER (10)
  );

ALTER TABLE CTX_ATTACHMENTS ADD CONSTRAINT CTX_ATTACHMENTS_PK PRIMARY KEY ( ID );

CREATE TABLE CTX_ATTACHMENT_TYPES
  (
    ID          NUMBER (10) NOT NULL ,
    VERSION     NUMBER (10) NOT NULL ,
    INSERT_TIME DATE DEFAULT sysdate NOT NULL ,
    UPDATE_TIME DATE NOT NULL ,
    CODE        VARCHAR2 (50 BYTE) NOT NULL ,
    DESCRIPTION VARCHAR2 (255 BYTE) NOT NULL
  );

ALTER TABLE CTX_ATTACHMENT_TYPES ADD CONSTRAINT CTX_ATTACHMENT_TYPES_PK PRIMARY KEY ( ID );

ALTER TABLE CTX_ATTACHMENT_TYPES ADD CONSTRAINT ATTACHMENT_TYPE_UN UNIQUE ( CODE );

CREATE TABLE CTX_CONTEXTS
  (
    ID          NUMBER (10) NOT NULL ,
    VERSION     NUMBER (10) NOT NULL ,
    INSERT_TIME DATE DEFAULT sysdate NOT NULL ,
    UPDATE_TIME DATE NOT NULL ,
    CLASS_NAME  VARCHAR2 (255 BYTE) NOT NULL
  );

ALTER TABLE CTX_CONTEXTS ADD CONSTRAINT CTX_CONTEXTS_PK PRIMARY KEY ( ID );

CREATE TABLE DRW_FLOORS
  (
    ID          NUMBER (10) NOT NULL ,
    VERSION     NUMBER (10) NOT NULL ,
    INSERT_TIME DATE DEFAULT sysdate NOT NULL ,
    UPDATE_TIME DATE NOT NULL ,
    NAME        VARCHAR2 (100 BYTE) ,
    DESCRIPTION VARCHAR2 (255 BYTE) ,
    "ORDER"     NUMBER ,
    WIDTH FLOAT ,
    HEIGHT FLOAT ,
    REF_CONTEXT      NUMBER (10) NOT NULL ,
    REF_ORGANIZATION NUMBER (10) NOT NULL
  );

CREATE UNIQUE INDEX DRW_FLOORS__IDX ON DRW_FLOORS
  (
    REF_CONTEXT ASC
  );

ALTER TABLE DRW_FLOORS ADD CONSTRAINT DRW_FLOORS_PK PRIMARY KEY ( ID );

CREATE TABLE DRW_SHAPES
  (
    ID          NUMBER (10) NOT NULL ,
    VERSION     NUMBER (10) NOT NULL ,
    INSERT_TIME DATE DEFAULT sysdate NOT NULL ,
    UPDATE_TIME DATE NOT NULL ,
    TYPE        VARCHAR2 (20 BYTE) ,
    START_X FLOAT ,
    START_Y FLOAT ,
    SIZE_X FLOAT ,
    SIZE_Y FLOAT ,
    RADIUS FLOAT ,
    "ORDER" NUMBER
  );

ALTER TABLE DRW_SHAPES ADD CONSTRAINT DRW_SHAPES_PK PRIMARY KEY ( ID );

CREATE TABLE EQP_EQUIPMENTS
  (
    ID                            NUMBER (10) NOT NULL ,
    VERSION                       NUMBER (10) NOT NULL ,
    INSERT_TIME                   DATE DEFAULT sysdate NOT NULL ,
    UPDATE_TIME                   DATE NOT NULL ,
    NAME                          VARCHAR2 (100 BYTE) ,
    DESCRIPTION                   VARCHAR2 (255 BYTE) ,
    REF_EQUIPMENTS_EQUIPMENTTYPES NUMBER (10) NOT NULL
  );

ALTER TABLE EQP_EQUIPMENTS ADD CONSTRAINT EQP_EQUIPMENTS_PK PRIMARY KEY ( ID, REF_EQUIPMENTS_EQUIPMENTTYPES );

CREATE TABLE EQP_EQUIPMENTTYPES
  (
    ID               NUMBER (10) NOT NULL ,
    VERSION          NUMBER (10) NOT NULL ,
    INSERT_TIME      DATE DEFAULT sysdate NOT NULL ,
    UPDATE_TIME      DATE NOT NULL ,
    NAME             VARCHAR2 (100 BYTE) ,
    DESCRIPTION      VARCHAR2 (255 BYTE) ,
    REF_ORGANIZATION NUMBER (10) NOT NULL
  );

ALTER TABLE EQP_EQUIPMENTTYPES ADD CONSTRAINT EQP_EQUIPMENTTYPES_PK PRIMARY KEY ( ID );

CREATE TABLE ORG_ORGANIZATIONS
  (
    ID               NUMBER (10) NOT NULL ,
    VERSION          NUMBER (10) NOT NULL ,
    INSERT_TIME      DATE DEFAULT sysdate NOT NULL ,
    UPDATE_TIME      DATE NOT NULL ,
    NAME             VARCHAR2 (80 BYTE) NOT NULL ,
    VAT_NUMBER       VARCHAR2 (50 BYTE) NOT NULL ,
    LEGAL_RESIDENCE  VARCHAR2 (80 BYTE) NOT NULL ,
    EMAIL            VARCHAR2 (80 BYTE) NOT NULL ,
    PHONE            VARCHAR2 (30 BYTE) NOT NULL ,
    STATUS           VARCHAR2 (50 BYTE) ,
    REF_ORGANIZATION NUMBER (10) NOT NULL
  );

ALTER TABLE ORG_ORGANIZATIONS ADD CONSTRAINT ORG_ORGANIZATIONS_PK PRIMARY KEY ( ID );

CREATE TABLE PRP_AIRCONDITIONING
  (
    ID                        NUMBER (10) NOT NULL ,
    VERSION                   NUMBER (10) NOT NULL ,
    INSERT_TIME               DATE DEFAULT sysdate NOT NULL ,
    UPDATE_TIME               DATE NOT NULL ,
    NAME                      VARCHAR2 (100 BYTE) ,
    DESCRIPTION               VARCHAR2 (255 BYTE) ,
    REF_PREREQUISITE_LAYOUTS  NUMBER (10) NOT NULL ,
    REF_PREREQUISITE_LAYOUTS1 NUMBER (10) NOT NULL ,
    REF_PREREQUISITE_LAYOUTS2 NUMBER (10) NOT NULL ,
    REF_DRAWING_SHAPES        NUMBER (10) NOT NULL
  );

CREATE UNIQUE INDEX PRP_AIRCONDITIONING__IDX ON PRP_AIRCONDITIONING
  (
    REF_DRAWING_SHAPES ASC
  );

ALTER TABLE PRP_AIRCONDITIONING ADD CONSTRAINT PRP_AIRCONDITIONING_PK PRIMARY KEY ( ID );

CREATE TABLE PRP_CLEANINGS
  (
    ID                        NUMBER (10) NOT NULL ,
    VERSION                   NUMBER (10) NOT NULL ,
    INSERT_TIME               DATE DEFAULT sysdate NOT NULL ,
    UPDATE_TIME               DATE NOT NULL ,
    NAME                      VARCHAR2 (100 BYTE) ,
    DESCRIPTION               VARCHAR2 (255 BYTE) ,
    REF_DRAWING_SHAPES        NUMBER (10) NOT NULL ,
    REF_PREREQUISITE_LAYOUTS  NUMBER (10) NOT NULL ,
    REF_PREREQUISITE_LAYOUTS1 NUMBER (10) NOT NULL ,
    REF_PREREQUISITE_LAYOUTS2 NUMBER (10) NOT NULL
  );

CREATE UNIQUE INDEX PRP_CLEANINGS__IDX ON PRP_CLEANINGS
  (
    REF_DRAWING_SHAPES ASC
  );

ALTER TABLE PRP_CLEANINGS ADD CONSTRAINT PRP_CLEANINGS_PK PRIMARY KEY ( ID );

CREATE TABLE PRP_EQUIPMENTS
  (
    ID                        NUMBER (10) NOT NULL ,
    VERSION                   NUMBER (10) NOT NULL ,
    INSERT_TIME               DATE DEFAULT sysdate NOT NULL ,
    UPDATE_TIME               DATE NOT NULL ,
    NAME                      VARCHAR2 (100 BYTE) ,
    DESCRIPTION               VARCHAR2 (255 BYTE) ,
    REF_EQUIPMENTS            NUMBER (10) NOT NULL ,
    REF_PREREQUISITE_LAYOUTS  NUMBER (10) NOT NULL ,
    REF_PREREQUISITE_LAYOUTS1 NUMBER (10) NOT NULL ,
    REF_PREREQUISITE_LAYOUTS2 NUMBER (10) NOT NULL ,
    REF_DRAWING_SHAPES        NUMBER (10) NOT NULL ,
    REF_EQUIPMENTS1           NUMBER (10) NOT NULL
  );

CREATE UNIQUE INDEX PRP_EQUIPMENTS__IDX ON PRP_EQUIPMENTS
  (
    REF_EQUIPMENTS ASC , REF_EQUIPMENTS1 ASC
  );

ALTER TABLE PRP_EQUIPMENTS ADD CONSTRAINT PRP_EQUIPMENTS_PK PRIMARY KEY ( ID );

CREATE TABLE PRP_LAYOUTS
  (
    ID                           NUMBER (10) NOT NULL ,
    VERSION                      NUMBER (10) NOT NULL ,
    INSERT_TIME                  DATE DEFAULT sysdate NOT NULL ,
    UPDATE_TIME                  DATE NOT NULL ,
    NAME                         VARCHAR2 (100 BYTE) ,
    DESCRIPTION                  VARCHAR2 (255 BYTE) ,
    REF_ORGANIZATION             NUMBER (10) NOT NULL ,
    REF_DRAWING_FLOORS           NUMBER (10) NOT NULL ,
    REF_DRAWING_SHAPES           NUMBER (10) NOT NULL ,
    REF_PREREQUISITE_RISKCLASSES NUMBER (10) NOT NULL
  );

CREATE UNIQUE INDEX PRP_LAYOUTS__IDX ON PRP_LAYOUTS
  (
    REF_PREREQUISITE_RISKCLASSES ASC
  );

CREATE UNIQUE INDEX PRP_LAYOUTS__IDXv1 ON PRP_LAYOUTS
  (
    REF_DRAWING_SHAPES ASC
  );

ALTER TABLE PRP_LAYOUTS ADD CONSTRAINT PRP_LAYOUTS_PK PRIMARY KEY ( ID, REF_ORGANIZATION, REF_DRAWING_FLOORS );

CREATE TABLE PRP_PESTCONTROLS
  (
    ID                        NUMBER (10) NOT NULL ,
    VERSION                   NUMBER (10) NOT NULL ,
    INSERT_TIME               DATE DEFAULT sysdate NOT NULL ,
    UPDATE_TIME               DATE NOT NULL ,
    NAME                      VARCHAR2 (100 BYTE) ,
    DESCRIPTION               VARCHAR2 (255 BYTE) ,
    REF_PREREQUISITE_LAYOUTS  NUMBER (10) NOT NULL ,
    REF_PREREQUISITE_LAYOUTS1 NUMBER (10) NOT NULL ,
    REF_PREREQUISITE_LAYOUTS2 NUMBER (10) NOT NULL ,
    REF_DRAWING_SHAPES        NUMBER (10) NOT NULL
  );

CREATE UNIQUE INDEX PRP_PESTCONTROLS__IDX ON PRP_PESTCONTROLS
  (
    REF_DRAWING_SHAPES ASC
  );

ALTER TABLE PRP_PESTCONTROLS ADD CONSTRAINT PRP_PESTCONTROLS_PK PRIMARY KEY ( ID );

CREATE TABLE PRP_RISKCLASSES
  (
    ID               NUMBER (10) NOT NULL ,
    VERSION          NUMBER (10) NOT NULL ,
    INSERT_TIME      DATE DEFAULT sysdate NOT NULL ,
    UPDATE_TIME      DATE NOT NULL ,
    NAME             VARCHAR2 (100 BYTE) ,
    DESCRIPTION      VARCHAR2 (255 BYTE) ,
    COLOR            VARCHAR2 (20) ,
    REF_ORGANIZATION NUMBER (10) NOT NULL
  );

ALTER TABLE PRP_RISKCLASSES ADD CONSTRAINT PRP_RISKCLASSES_PK PRIMARY KEY ( ID );

CREATE TABLE PRP_WASTEDISPOSALS
  (
    ID                        NUMBER (10) NOT NULL ,
    VERSION                   NUMBER (10) NOT NULL ,
    INSERT_TIME               DATE DEFAULT sysdate NOT NULL ,
    UPDATE_TIME               DATE NOT NULL ,
    NAME                      VARCHAR2 (100 BYTE) ,
    DESCRIPTION               VARCHAR2 (255 BYTE) ,
    REF_DRAWING_SHAPES        NUMBER (10) NOT NULL ,
    REF_PREREQUISITE_LAYOUTS  NUMBER (10) NOT NULL ,
    REF_PREREQUISITE_LAYOUTS1 NUMBER (10) NOT NULL ,
    REF_PREREQUISITE_LAYOUTS2 NUMBER (10) NOT NULL
  );

CREATE UNIQUE INDEX PRP_WASTEDISPOSALS__IDX ON PRP_WASTEDISPOSALS
  (
    REF_DRAWING_SHAPES ASC
  );

ALTER TABLE PRP_WASTEDISPOSALS ADD CONSTRAINT PRP_WASTEDISPOSALS_PK PRIMARY KEY ( ID, REF_PREREQUISITE_LAYOUTS, REF_PREREQUISITE_LAYOUTS1, REF_PREREQUISITE_LAYOUTS2 );

CREATE TABLE PRP_WATERSUPPLIES
  (
    ID                        NUMBER (10) NOT NULL ,
    VERSION                   NUMBER (10) NOT NULL ,
    INSERT_TIME               DATE DEFAULT sysdate NOT NULL ,
    UPDATE_TIME               DATE NOT NULL ,
    NAME                      VARCHAR2 (100 BYTE) ,
    DESCRIPTION               VARCHAR2 (255 BYTE) ,
    REF_PREREQUISITE_LAYOUTS  NUMBER (10) NOT NULL ,
    REF_DRAWING_SHAPES        NUMBER (10) NOT NULL ,
    REF_PREREQUISITE_LAYOUTS1 NUMBER (10) NOT NULL ,
    REF_PREREQUISITE_LAYOUTS2 NUMBER (10) NOT NULL
  );

CREATE UNIQUE INDEX PRP_WATERSUPPLIES__IDX ON PRP_WATERSUPPLIES
  (
    REF_DRAWING_SHAPES ASC
  );

ALTER TABLE PRP_WATERSUPPLIES ADD CONSTRAINT PRP_WATERSUPPLIES_PK PRIMARY KEY ( ID );

CREATE TABLE ROL_PROFILES
  (
    ID          NUMBER (10) NOT NULL ,
    INSERT_TIME TIMESTAMP NOT NULL ,
    UPDATE_TIME TIMESTAMP NOT NULL ,
    VERSION     NUMBER (10) ,
    NAME        VARCHAR2 (4000) NOT NULL
  );

ALTER TABLE ROL_PROFILES ADD CONSTRAINT ROL_PROFILES_PK PRIMARY KEY ( ID );

CREATE TABLE ROL_ROLES
  (
    ID               NUMBER (10) NOT NULL ,
    INSERT_TIME      TIMESTAMP NOT NULL ,
    UPDATE_TIME      TIMESTAMP NOT NULL ,
    VERSION          NUMBER (10) ,
    NAME             VARCHAR2 (4000) NOT NULL ,
    DESCRIPTION      VARCHAR2 (200) ,
    REF_ORGANIZATION NUMBER (10)
  );

ALTER TABLE ROL_ROLES ADD CONSTRAINT ROL_ROLES_PK PRIMARY KEY ( ID );

CREATE TABLE ROL_USERS
  (
    ID                   NUMBER (10) NOT NULL ,
    VERSION              NUMBER (10) NOT NULL ,
    INSERT_TIME          DATE DEFAULT sysdate NOT NULL ,
    UPDATE_TIME          DATE NOT NULL ,
    FIRSTNAME            VARCHAR2 (80 BYTE) NOT NULL ,
    LASTNAME             VARCHAR2 (80 BYTE) NOT NULL ,
    USERNAME             VARCHAR2 (80 BYTE) NOT NULL ,
    PASSWORD             VARCHAR2 (80 BYTE) NOT NULL ,
    PASSWORD_EXPIRE_DATE DATE ,
    EMAIL                VARCHAR2 (80 BYTE) ,
    PHONE                VARCHAR2 (30 BYTE) ,
    STATUS               VARCHAR2 (50 BYTE) DEFAULT 'VALID' ,
    LANGUAGE             VARCHAR2 (20) ,
    REF_ORGANIZATION     NUMBER (10) NOT NULL ,
    REF_ROL_ROLES        NUMBER (10) NOT NULL
  );

ALTER TABLE ROL_USERS ADD CONSTRAINT ROL_USERS_PK PRIMARY KEY ( ID );

ALTER TABLE ROL_USERS ADD CONSTRAINT USER_UN UNIQUE ( USERNAME );

CREATE TABLE ROL_USERS_ROL_PROFILES
  (
    REF_ROL_ROLES    NUMBER (10) NOT NULL ,
    REF_ROL_PROFILES NUMBER (10) NOT NULL
  )
  TABLESPACE TABLESPACE_DATA;

ALTER TABLE ROL_USERS_ROL_PROFILES ADD CONSTRAINT ROL_USERS_ROL_PROFILES__IDX PRIMARY KEY ( REF_ROL_ROLES, REF_ROL_PROFILES );

CREATE TABLE ROL_USER_RIGHTS
  (
    REF_ROL_PROFILES NUMBER (10) NOT NULL ,
    insert_time      TIMESTAMP NOT NULL ,
    update_time      TIMESTAMP NOT NULL ,
    version          NUMBER (10) ,
    NAME             VARCHAR2 (50)
  );

ALTER TABLE ROL_USER_RIGHTS ADD CONSTRAINT ROL_USER_RIGHTS_PK PRIMARY KEY ( REF_ROL_PROFILES );

ALTER TABLE CFG_EMAIL_PARAMETERS ADD CONSTRAINT CFG_EML_PARMS_CFG_EML_TMPLS_FK FOREIGN KEY ( REF_EMAIL_TEMPLATE ) REFERENCES CFG_EMAIL_TEMPLATES ( ID );

ALTER TABLE CFG_ORGANIZATION_PARAMETERS ADD CONSTRAINT CFG_ORGA_PARAMS_ORG_ORGAS_FK FOREIGN KEY ( REF_ORGANIZATION ) REFERENCES ORG_ORGANIZATIONS ( ID );

ALTER TABLE CTX_ATTACHMENTS ADD CONSTRAINT CTX_ATTACHS_CTX_CONTEXTS_FK FOREIGN KEY ( REF_CONTEXT ) REFERENCES CTX_CONTEXTS ( ID );

ALTER TABLE ROL_USERS_ROL_PROFILES ADD CONSTRAINT FK_ASS_7 FOREIGN KEY ( REF_ROL_ROLES ) REFERENCES ROL_ROLES ( ID );

ALTER TABLE ROL_USERS_ROL_PROFILES ADD CONSTRAINT FK_ASS_8 FOREIGN KEY ( REF_ROL_PROFILES ) REFERENCES ROL_PROFILES ( ID );

ALTER TABLE ROL_USERS ADD CONSTRAINT REF_ROLE FOREIGN KEY ( REF_ROL_ROLES ) REFERENCES ROL_ROLES ( ID );

ALTER TABLE ROL_ROLES ADD CONSTRAINT ROL_ORGS_ROL_ROLES FOREIGN KEY ( REF_ORGANIZATION ) REFERENCES ORG_ORGANIZATIONS ( ID );

ALTER TABLE ROL_USERS ADD CONSTRAINT ROL_USERS_ORG_ORGAS_FK FOREIGN KEY ( REF_ORGANIZATION ) REFERENCES ORG_ORGANIZATIONS ( ID );

ALTER TABLE ORG_ORGANIZATIONS ADD CONSTRAINT Relation_270 FOREIGN KEY ( REF_ORGANIZATION ) REFERENCES ORG_ORGANIZATIONS ( ID );

ALTER TABLE PRP_LAYOUTS ADD CONSTRAINT Relation_276 FOREIGN KEY ( REF_PREREQUISITE_RISKCLASSES ) REFERENCES PRP_RISKCLASSES ( ID );

ALTER TABLE DRW_FLOORS ADD CONSTRAINT Relation_278 FOREIGN KEY ( REF_CONTEXT ) REFERENCES CTX_CONTEXTS ( ID );

ALTER TABLE PRP_LAYOUTS ADD CONSTRAINT Relation_281 FOREIGN KEY ( REF_ORGANIZATION ) REFERENCES ORG_ORGANIZATIONS ( ID );

ALTER TABLE DRW_FLOORS ADD CONSTRAINT Relation_282 FOREIGN KEY ( REF_ORGANIZATION ) REFERENCES ORG_ORGANIZATIONS ( ID );

ALTER TABLE PRP_LAYOUTS ADD CONSTRAINT Relation_283 FOREIGN KEY ( REF_DRAWING_FLOORS ) REFERENCES DRW_FLOORS ( ID );

ALTER TABLE PRP_WATERSUPPLIES ADD CONSTRAINT Relation_285 FOREIGN KEY ( REF_PREREQUISITE_LAYOUTS, REF_PREREQUISITE_LAYOUTS1, REF_PREREQUISITE_LAYOUTS2 ) REFERENCES PRP_LAYOUTS ( ID, REF_ORGANIZATION, REF_DRAWING_FLOORS );

ALTER TABLE PRP_LAYOUTS ADD CONSTRAINT Relation_287 FOREIGN KEY ( REF_DRAWING_SHAPES ) REFERENCES DRW_SHAPES ( ID );

ALTER TABLE PRP_WATERSUPPLIES ADD CONSTRAINT Relation_288 FOREIGN KEY ( REF_DRAWING_SHAPES ) REFERENCES DRW_SHAPES ( ID );

ALTER TABLE PRP_AIRCONDITIONING ADD CONSTRAINT Relation_290 FOREIGN KEY ( REF_PREREQUISITE_LAYOUTS, REF_PREREQUISITE_LAYOUTS1, REF_PREREQUISITE_LAYOUTS2 ) REFERENCES PRP_LAYOUTS ( ID, REF_ORGANIZATION, REF_DRAWING_FLOORS );

ALTER TABLE PRP_AIRCONDITIONING ADD CONSTRAINT Relation_291 FOREIGN KEY ( REF_DRAWING_SHAPES ) REFERENCES DRW_SHAPES ( ID );

ALTER TABLE PRP_WASTEDISPOSALS ADD CONSTRAINT Relation_292 FOREIGN KEY ( REF_DRAWING_SHAPES ) REFERENCES DRW_SHAPES ( ID );

ALTER TABLE PRP_WASTEDISPOSALS ADD CONSTRAINT Relation_293 FOREIGN KEY ( REF_PREREQUISITE_LAYOUTS, REF_PREREQUISITE_LAYOUTS1, REF_PREREQUISITE_LAYOUTS2 ) REFERENCES PRP_LAYOUTS ( ID, REF_ORGANIZATION, REF_DRAWING_FLOORS );

ALTER TABLE PRP_CLEANINGS ADD CONSTRAINT Relation_294 FOREIGN KEY ( REF_DRAWING_SHAPES ) REFERENCES DRW_SHAPES ( ID );

ALTER TABLE PRP_CLEANINGS ADD CONSTRAINT Relation_295 FOREIGN KEY ( REF_PREREQUISITE_LAYOUTS, REF_PREREQUISITE_LAYOUTS1, REF_PREREQUISITE_LAYOUTS2 ) REFERENCES PRP_LAYOUTS ( ID, REF_ORGANIZATION, REF_DRAWING_FLOORS );

ALTER TABLE EQP_EQUIPMENTS ADD CONSTRAINT Relation_298 FOREIGN KEY ( REF_EQUIPMENTS_EQUIPMENTTYPES ) REFERENCES EQP_EQUIPMENTTYPES ( ID );

ALTER TABLE PRP_EQUIPMENTS ADD CONSTRAINT Relation_299 FOREIGN KEY ( REF_EQUIPMENTS, REF_EQUIPMENTS1 ) REFERENCES EQP_EQUIPMENTS ( ID, REF_EQUIPMENTS_EQUIPMENTTYPES );

ALTER TABLE PRP_EQUIPMENTS ADD CONSTRAINT Relation_300 FOREIGN KEY ( REF_PREREQUISITE_LAYOUTS, REF_PREREQUISITE_LAYOUTS1, REF_PREREQUISITE_LAYOUTS2 ) REFERENCES PRP_LAYOUTS ( ID, REF_ORGANIZATION, REF_DRAWING_FLOORS );

ALTER TABLE PRP_EQUIPMENTS ADD CONSTRAINT Relation_301 FOREIGN KEY ( REF_DRAWING_SHAPES ) REFERENCES DRW_SHAPES ( ID );

ALTER TABLE PRP_PESTCONTROLS ADD CONSTRAINT Relation_302 FOREIGN KEY ( REF_PREREQUISITE_LAYOUTS, REF_PREREQUISITE_LAYOUTS1, REF_PREREQUISITE_LAYOUTS2 ) REFERENCES PRP_LAYOUTS ( ID, REF_ORGANIZATION, REF_DRAWING_FLOORS );

ALTER TABLE PRP_PESTCONTROLS ADD CONSTRAINT Relation_303 FOREIGN KEY ( REF_DRAWING_SHAPES ) REFERENCES DRW_SHAPES ( ID );

ALTER TABLE EQP_EQUIPMENTTYPES ADD CONSTRAINT Relation_305 FOREIGN KEY ( REF_ORGANIZATION ) REFERENCES ORG_ORGANIZATIONS ( ID );

ALTER TABLE ROL_USER_RIGHTS ADD CONSTRAINT fk_profiles_users_rights FOREIGN KEY ( REF_ROL_PROFILES ) REFERENCES ROL_PROFILES ( ID );


 -- Script importati da Adjustment.sql, non gestiti da DataModel



